<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>__GROUP_ID__</groupId>
        <artifactId>__ARTIFACT_ID__</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>__ARTIFACT_ID__-app</artifactId>
    <name>__PROJECT_NAME__-app</name>

    <dependencies>
        <dependency>
            <groupId>__GROUP_ID__</groupId>
            <artifactId>__ARTIFACT_ID__-client</artifactId>
        </dependency>
        <dependency>
            <groupId>__GROUP_ID__</groupId>
            <artifactId>__ARTIFACT_ID__-domain</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-dto</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>
</project>
